### Get all prdoducts
GET http://localhost:8000/products
Content-Type: application/json

### Get product by id
GET http://localhost:8000/products/345
Content-Type: application/json

### Get shopping cart
GET http://localhost:8000/users/0001/cart
Content-Type: application/json

### Add to shopping cart
POST http://localhost:8000/users/0001/cart
Content-Type: application/json

{
  "id": "789"
}

### Delete product from shopping cart
DELETE http://localhost:8000/users/0001/cart/789
Content-Type: application/json